{% set version = "0.6.2" %}

package:
  name: openapi-schema-validator
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openapi-schema-validator/openapi_schema_validator-{{ version }}.tar.gz
  sha256: 11a95c9c9017912964e3e5f2545a5b11c3814880681fcacfb73b1759bb4f2804

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - jsonschema >=4.19.1,<5.0.0a0
    - jsonschema-specifications >=2023.5.2,<2024.0.0
    - python >={{ python_min }}
    - rfc3339-validator

test:
  source_files:
    - tests
  imports:
    - openapi_schema_validator
  commands:
    - pip check
    - pytest -vv --cov=openapi_schema_validator --cov-branch --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=80
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
