{% set version = "0.6.3" %}

package:
  name: openapi-schema-validator
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/o/openapi-schema-validator/openapi_schema_validator-{{ version }}.tar.gz
  sha256: f37bace4fc2a5d96692f4f8b31dc0f8d7400fd04f3a937798eaf880d425de6ee

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - jsonschema >=4.19.1,<5.0.0a0
    - jsonschema-specifications >=2023.5.2
    - python >={{ python_min }}
    - rfc3339-validator

test:
  source_files:
    - tests
  requires:
    - coverage
    - pip
    - pytest
    - python {{ python_min }}
  imports:
    - openapi_schema_validator
  commands:
    - pip check
    - coverage run --source=openapi_schema_validator --branch -m pytest -vv --tb=long --color=yes -k "not test_array_prefixitems_invalid"
    - coverage report --show-missing --skip-covered --fail-under=80

about:
  home: https://github.com/p1c2u/openapi-schema-validator
  summary: OpenAPI schema validation for Python
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bollwyvl
